name: Run AI Stock Simulator

on:
  schedule:
    # 平日 朝6:00（日本時間）＝ UTC 21:00 前日
    - cron: '0 21 * * 1-5'
  workflow_dispatch:

jobs:
  run-simulator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q yfinance lightgbm scikit-learn pandas numpy matplotlib requests

      - name: Run production simulation
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python run_production_day.py
